[general]
base_url = "http://70.23.102.189:3030"
num_cuda_devices = 1
miner_id_0 = "sd-miner-v0.0.2"
log_filename = "sd-miner.log"

s3_bucket = 'heurist-images'
model_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/models.json"
vae_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/vae.json"
base_dir = "~/.cache/heurist"
min_deadline = 1
