[service]
base_url = "http://sequencer.heurist.xyz"
llm_url = "http://localhost"
signal_url = "https://d2k7cjzmjgpm6p.cloudfront.net/prod/"
vllm_port = 8000

[logging]
sd_log_filename = "sd-miner.log"
llm_log_filename = "llm-miner.log"

[versions]
sd_version = "sd-v1.1.0"
llm_version = "llm-1.0.0"

[storage]
s3_bucket = 'heurist-images'
base_dir = "~/.cache/heurist"

[model_config]
model_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/models.json"
vae_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/vae.json"

[system]
num_cuda_devices = 1
num_child_process = 2
sleep_duration = 2
min_deadline = 1
reload_interval = 600
gpu_ids = "0" # Specify GPUs to use here. Example: "0,1" for GPUs 0 and 1.

[processing_limits]
max_iterations = 50
max_width = 1024
max_height = 1024
